### ISSUE TITLE
Esearchresults model should capture type of lookup performed

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Dynamodb-Model#2]
## Problem

As per [this issue](https://github.com/wcmc-its/ReCiter/issues/454), we need a reliable source of article count.

## Solution

When lookups are performed and stored in the esearchresults table, add an additional attribute called `lookup_type` (or whatever you want). The two enum values should be ALL_PUBLICATIONS and ONLY_NEWLY_ADDED_PUBLICATIONS (AKA incremental).

**Comment by sarbajitdutta** [comment]
This has been fixed with release of v2.0.8 to maven central
